/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tampilan;

import com.formdev.flatlaf.FlatLightLaf;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import koneksi.Koneksi;

/**
 *
 * @author angga murdika
 */
public class form_supplier extends javax.swing.JFrame {

    /**
     * Creates new form form_barang
     */
    Connection conn;
    public form_supplier() {
        initComponents();
        Koneksi koneksi1 = new Koneksi();
        conn = koneksi1.connect();
        txtNamaSupplier.putClientProperty("JTextField.placeholderText", "Masukkan Username");
        txtTelepon.putClientProperty("JTextField.placeholderText", "Masukkan No. Hp");
    }

    private Runnable onDataSaved;

    public form_supplier(Runnable onDataSaved) {
        this();
        this.onDataSaved = onDataSaved;
    }
    
    public void setFormData(String id, String nama, String telp, String alamat) {
        txtNamaSupplier.setText(nama);
        txtTelepon.setText(telp);
        txtAlamat.setText(alamat);

        btnSimpan.setText("Update");
        btnSimpan.removeActionListener(btnSimpan.getActionListeners()[0]);
        btnSimpan.addActionListener(evt -> {
            String sql = "UPDATE pemasok SET nama_pemasok=?, no_tlp=?, alamat=? WHERE id_pemasok=?";
            try {
                PreparedStatement stmt = conn.prepareStatement(sql);
                stmt.setString(1, txtNamaSupplier.getText());
                stmt.setString(2, txtTelepon.getText());
                stmt.setString(3, txtAlamat.getText());
                stmt.setString(4, id);
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data diupdate!");
                if (onDataSaved != null) onDataSaved.run();
                dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Update gagal: " + ex.getMessage());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTab = new javax.swing.JLabel();
        lbNamaSupplier = new javax.swing.JLabel();
        txtNamaSupplier = new javax.swing.JTextField();
        lbPhone = new javax.swing.JLabel();
        txtTelepon = new javax.swing.JTextField();
        lbAlamat = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        btnSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbTab.setFont(new java.awt.Font("SF Pro Text", 1, 24)); // NOI18N
        lbTab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTab.setText("Supplier");
        lbTab.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lbNamaSupplier.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        lbNamaSupplier.setText("Nama Supplier");

        txtNamaSupplier.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        txtNamaSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaSupplierActionPerformed(evt);
            }
        });

        lbPhone.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        lbPhone.setText("Phone");

        txtTelepon.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        txtTelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeleponActionPerformed(evt);
            }
        });

        lbAlamat.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        lbAlamat.setText("Alamat");

        txtAlamat.setColumns(20);
        txtAlamat.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        txtAlamat.setRows(3);
        jScrollPane1.setViewportView(txtAlamat);

        btnSimpan.setBackground(new java.awt.Color(0, 204, 51));
        btnSimpan.setFont(new java.awt.Font("SF Pro Text", 1, 12)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbTab, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(lbNamaSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNamaSupplier)
                            .addComponent(txtTelepon)
                            .addComponent(lbAlamat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(lbTab)
                .addGap(18, 18, 18)
                .addComponent(lbNamaSupplier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNamaSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPhone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbAlamat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaSupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaSupplierActionPerformed

    private void txtTeleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeleponActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String nama = txtNamaSupplier.getText();
        String noTlp = txtTelepon.getText();
        String alamat = txtAlamat.getText();
        String idBaru = IDGenerator.generateAutoID(conn, "pemasok", "id_pemasok", "PMS", 3);
        
        String sql = "INSERT INTO pemasok (nama_pemasok, no_tlp, alamat, id_pemasok) VALUES (?, ?, ?, ?)";

        try {
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, nama);
            stmt.setString(2, noTlp);
            stmt.setString(3, alamat);
            stmt.setString(4, idBaru);
            
            int rowsInserted = stmt.executeUpdate();
            if (rowsInserted > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");
                txtNamaSupplier.setText("");
                txtTelepon.setText("");
                txtAlamat.setText("");

                if (onDataSaved != null) {
                    onDataSaved.run(); // ← refresh dashboard
                }
                dispose(); // ← tutup form
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menambahkan data: " + e.getMessage());
        }
        
        
    }//GEN-LAST:event_btnSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new form_supplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAlamat;
    private javax.swing.JLabel lbNamaSupplier;
    private javax.swing.JLabel lbPhone;
    private javax.swing.JLabel lbTab;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtNamaSupplier;
    private javax.swing.JTextField txtTelepon;
    // End of variables declaration//GEN-END:variables
}
