/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tampilan;

import com.formdev.flatlaf.FlatLightLaf;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import koneksi.Koneksi;
import md5.md5;

public class form_karyawan extends javax.swing.JFrame {

    Connection conn;

    public form_karyawan() {
        initComponents();
        Koneksi koneksi1 = new Koneksi();
        conn = koneksi1.connect();
        setLocationRelativeTo(null);
    }

    private Runnable onDataSaved;

    public form_karyawan(Runnable onDataSaved) {
        this();
        this.onDataSaved = onDataSaved;
    }

    public void setFormData(String id, String email, String password, String nama, String telpon, String role, String status) {
        txtEmail.setText(email);
        txtPassword.setText(password);
        txtNama.setText(nama);
        txtTelepon.setText(telpon);
        dropRole.setSelectedItem(role);
        dropStatus.setSelectedItem(status);

        btnSimpan.setText("Update");
        btnSimpan.removeActionListener(btnSimpan.getActionListeners()[0]);
        btnSimpan.addActionListener(evt -> {
            String sql = "UPDATE karyawan SET email=?, password=?, nama_karyawan=?, no_tlp=?, role=?, status=? WHERE id_karyawan=?";
            try {
                PreparedStatement stmt = conn.prepareStatement(sql);
                stmt.setString(1, txtEmail.getText());
                stmt.setString(2, md5.md5(txtPassword.getText()));
                stmt.setString(3, txtNama.getText());
                stmt.setString(4, txtTelepon.getText());
                stmt.setString(5, dropRole.getSelectedItem().toString());
                stmt.setString(6, dropStatus.getSelectedItem().toString());
                stmt.setString(7, id);
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data diupdate!");
                if (onDataSaved != null) {
                    onDataSaved.run();
                }
                dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Update gagal: " + ex.getMessage());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        txtNama1 = new javax.swing.JTextField();
        txtTelepon1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        labelPassword = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dropRole = new javax.swing.JComboBox<>();
        btnSimpan = new javax.swing.JButton();
        dropStatus = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        labelNama = new javax.swing.JLabel();
        txtTelepon = new javax.swing.JTextField();
        labelTelepon = new javax.swing.JLabel();

        jLabel9.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        jLabel9.setLabelFor(txtPassword);
        jLabel9.setText("No. Telepon");

        txtNama1.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        txtNama1.setPreferredSize(new java.awt.Dimension(64, 23));
        txtNama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNama1ActionPerformed(evt);
            }
        });

        txtTelepon1.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        txtTelepon1.setPreferredSize(new java.awt.Dimension(64, 23));
        txtTelepon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelepon1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        jLabel8.setLabelFor(txtEmail);
        jLabel8.setText("Nama");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("SF Pro Text", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Karyawan");

        txtEmail.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        txtEmail.setPreferredSize(new java.awt.Dimension(64, 23));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        labelEmail.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        labelEmail.setLabelFor(txtEmail);
        labelEmail.setText("Email");

        txtPassword.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        txtPassword.setPreferredSize(new java.awt.Dimension(64, 23));
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        labelPassword.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        labelPassword.setLabelFor(txtPassword);
        labelPassword.setText("Password");

        jLabel4.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        jLabel4.setLabelFor(dropRole);
        jLabel4.setText("role");

        dropRole.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        dropRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "user", " " }));
        dropRole.setPreferredSize(new java.awt.Dimension(91, 23));
        dropRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropRoleActionPerformed(evt);
            }
        });

        btnSimpan.setBackground(new java.awt.Color(0, 204, 51));
        btnSimpan.setFont(new java.awt.Font("SF Pro Text", 1, 12)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        dropStatus.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        dropStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktif", "Tidak Aktif" }));
        dropStatus.setPreferredSize(new java.awt.Dimension(91, 23));
        dropStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropStatusActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        jLabel7.setLabelFor(dropRole);
        jLabel7.setText("Status");

        txtNama.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        txtNama.setPreferredSize(new java.awt.Dimension(64, 23));
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        labelNama.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        labelNama.setLabelFor(txtEmail);
        labelNama.setText("Nama");

        txtTelepon.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        txtTelepon.setPreferredSize(new java.awt.Dimension(64, 23));
        txtTelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeleponActionPerformed(evt);
            }
        });

        labelTelepon.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        labelTelepon.setLabelFor(txtPassword);
        labelTelepon.setText("No. Telepon");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelEmail)
                        .addComponent(labelPassword)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addComponent(dropRole, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dropStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addComponent(labelNama)
                        .addComponent(labelTelepon)
                        .addComponent(txtTelepon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(78, 78, 78))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(labelEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(labelPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(labelTelepon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dropRole, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dropStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String email = txtEmail.getText();
        String password = md5.md5(txtPassword.getText());
        String nama = txtNama.getText();
        String telpon = txtTelepon.getText();
        String role = dropRole.getSelectedItem().toString();
        String status = dropStatus.getSelectedItem().toString();
        String idBaru = IDGenerator.generateAutoID(conn, "karyawan", "id_karyawan", "KRY", 3);   
        String sql = "INSERT INTO karyawan (email, password, nama_karyawan, no_tlp, role, status, id_karyawan) VALUES (?, ?, ?, ?, ?, ?, ?)";

        try {
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, email);
            stmt.setString(2, password);
            stmt.setString(3, nama);
            stmt.setString(4, telpon);
            stmt.setString(5, role);
            stmt.setString(6, status);
            stmt.setString(7, idBaru);

            int rowsInserted = stmt.executeUpdate();
            if (rowsInserted > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");
                txtEmail.setText("");
                txtPassword.setText("");
                txtNama.setText("");
                txtTelepon.setText("");
                dropRole.setSelectedIndex(0);
                dropStatus.setSelectedIndex(0);

                if (onDataSaved != null) {
                    onDataSaved.run();
                }
                dispose(); 
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menambahkan data: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void dropRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropRoleActionPerformed

    private void dropStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropStatusActionPerformed

    private void txtNama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNama1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNama1ActionPerformed

    private void txtTelepon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelepon1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelepon1ActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtTeleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeleponActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        FlatLightLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_karyawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> dropRole;
    private javax.swing.JComboBox<String> dropStatus;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelTelepon;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNama1;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtTelepon;
    private javax.swing.JTextField txtTelepon1;
    // End of variables declaration//GEN-END:variables
}
